/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-09-13 15:59:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wyyf.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lys.utils.pagination.PageBean;
import java.util.Map;
import java.util.List;
import com.lys.utils.*;

public final class changeCity_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/wyyf/index/foot.jsp", Long.valueOf(1440655812758L));
    _jspx_dependants.put("/WEB-INF/jsp/wyyf/index/top.jsp", Long.valueOf(1441591596802L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header['host']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("<meta property=\"qc:admins\" content=\"234163277067167207676375716450\" />\r\n");
      out.write("<title>我要验房</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"我要验房,我要设计,我要装修,找工长,找师傅,我要建材,我要家具,我要监理,我要检测,验房,网众验房,设计，装修，建材，家具，监理管家，空气检测，装修管家\"/>\r\n");
      out.write("<meta name=\"Description\" content=\"中国第一家专业挂牌验房机构，互联网+验房\"/>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/ico/ico.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/c1/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/c1/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/c1/layout.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/c1/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/c1/laydate.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/j1/jquery/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/j1/jquery/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/j1/jquery/superSlide.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/j1/main.js?v1.0\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/j1/laydate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/eshop/pingpp_pay.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/eshop/alipay_in_weixin/ap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/eshop/avalon.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var _hmt = _hmt || [];\r\n");
      out.write("(function() {\r\n");
      out.write("  var hm = document.createElement(\"script\");\r\n");
      out.write("  hm.src = \"//hm.baidu.com/hm.js?ed0a53e9a41e0024fb668a5734f58b19\";\r\n");
      out.write("  var s = document.getElementsByTagName(\"script\")[0];\r\n");
      out.write("  s.parentNode.insertBefore(hm, s);\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 表单附带文件上传 局部刷新需要的JS -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.easyui.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/* function checkLoginUser(rid,sid){\r\n");
      out.write("\tvar oldRequestUrl=window.location.href;\r\n");
      out.write("\tvar userid=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\talert(userid);\r\n");
      out.write("\tif(userid==null||userid==''){\r\n");
      out.write("\t\talert(\"当前未登陆请先登陆!\");\r\n");
      out.write("\t\tlocation.href=\"index/loginp?oldRequestUrl=\"+oldRequestUrl;\r\n");
      out.write("\t}else{\t\r\n");
      out.write("\t\tlocation.href=\"index/toDesign?rid=\"+rid+\"&sid=\"+sid;\r\n");
      out.write("\t}\r\n");
      out.write("} */\r\n");
      out.write("$(function(){\r\n");
      out.write("    //推荐工长\r\n");
      out.write("\t$(\"#temp4\").Slide({\r\n");
      out.write("\t\teffect : \"scroolLoop\",\r\n");
      out.write("\t\tautoPlay:false,\r\n");
      out.write("    \tspeed : \"normal\",\r\n");
      out.write("\t\ttimer : 3000,\r\n");
      out.write("\t\tsteps:2\r\n");
      out.write("\t});\r\n");
      out.write("\t//装修贷\r\n");
      out.write("  /*   $(\"#temp6\").Slide({\r\n");
      out.write("\t\teffect : \"scroolY\",\r\n");
      out.write("    \tspeed : \"normal\",\r\n");
      out.write("\t\ttimer : 3000\r\n");
      out.write("\t}); */\r\n");
      out.write("\t//推荐师傅\r\n");
      out.write("\t$(\"#temp8\").Slide({\r\n");
      out.write("\t\teffect : \"scroolLoop\",\r\n");
      out.write("\t\tautoPlay:false,\r\n");
      out.write("    \tspeed : \"normal\",\r\n");
      out.write("\t\ttimer : 3000,\r\n");
      out.write("\t\tsteps:2\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("//统计代码\r\n");
      out.write("var _hmt = _hmt || [];\r\n");
      out.write("(function() {\r\n");
      out.write("  var hm = document.createElement(\"script\");\r\n");
      out.write("  hm.src = \"//hm.baidu.com/hm.js?ed0a53e9a41e0024fb668a5734f58b19\";\r\n");
      out.write("  var s = document.getElementsByTagName(\"script\")[0]; \r\n");
      out.write("  s.parentNode.insertBefore(hm, s);\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body  ms-controller=\"box\">\r\n");
      out.write("<!--top-->\r\n");
      out.write("<div id=\"top\" class=\"f_wh100\">\r\n");
      out.write("\t <div class=\"header header_ps\">\r\n");
      out.write("\t\t\t<div class=\"header_psson\">\r\n");
      out.write("\t\t\t\t<div class=\"head-top clear\">\r\n");
      out.write("\t\t\t\t<dl style=\"float: left;width: 50%;\">\r\n");
      out.write("\t                <dt id=\"Your_city\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CurrentCityInfo.d_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</dt>\r\n");
      out.write("\t                <dd>[<a href=\"index/changeCity\">切换城市</a>]</dd>\r\n");
      out.write("\t            </dl>\r\n");
      out.write("\t\t\t\t\t<dl class=\"index_topdl clearfix\" style=\"float:right;width:50%;\">\r\n");
      out.write("\t\t\t\t\t\t <dd class=\"last\"  style=\"float:right\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index/buyCart\">我的购物车</a>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<dd style=\"float:right\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mycontainer\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <div class=\"head-middle clear clearfix\">\r\n");
      out.write("                <a href=\"index\" class=\"logo f_db f_fl\">\r\n");
      out.write("                    <img src=\"images/a_06.png\" alt=\"\" height=\"59\" width=\"303\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"search f_fl\">\r\n");
      out.write("                    <form action=\"index/ProductList\" method=\"Get\" >\r\n");
      out.write("                    <p class=\"s_form clear\">\r\n");
      out.write("                        <input class=\"keywords\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keywords}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"keywords\" type=\"text\">\r\n");
      out.write("                        <input class=\"subBtn\" value=\"搜索\"  type=\"submit\">\r\n");
      out.write("                    </p>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"index-tell f_fr\">\r\n");
      out.write("                    <img src=\"images/call_05.png\" class=\"f_fl\" alt=\"\" height=\"48\" width=\"48\">\r\n");
      out.write("                    <dl class=\"f_fl\" style=\"text-align: center\">\r\n");
      out.write("                        <dt>网众科技客服热线</dt>\r\n");
      out.write("                        <dd>400-028-5998</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"f_wh100 nav-box\">\r\n");
      out.write("    <div class=\"mycontainer\">\r\n");
      out.write("        <ul class=\"mynav clear \">\r\n");
      out.write("            <li><a href=\"index?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"mynav-a\">首页</a></li>\r\n");
      out.write("            <li><a class=\"mynav-a\" href=\"index/checkfree?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">我要验房<span></span></a>\r\n");
      out.write("                <ul style=\"display: none;\" class=\"mynav_son\">\r\n");
      out.write("                    <li><a href=\"index/checkfree?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">免费验房</a></li>\r\n");
      out.write("                    <li><a href=\"index/checkgold?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">金牌验房</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a class=\"mynav-a\" href=\"index/toDesign?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">我要设计<span></span></a>\r\n");
      out.write("                <ul class=\"mynav_son\">\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <li><a href=\"index/workmessjsp?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">户型优化</a></li>\r\n");
      out.write("                    <li><a href=\"index/designstyle?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">个性设计</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a class=\"mynav-a\" href=\"index/overman?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">我要装修</a><span></span>\r\n");
      out.write("                <ul class=\"mynav_son\">\r\n");
      out.write("                    <li><a href=\"index/overman?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">找工长</a></li>\r\n");
      out.write("                    <li><a href=\"index/master?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">找师傅</a></li>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a class=\"mynav-a\" href=\"index/shopcheap?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">我要特价<span></span></a></li>\r\n");
      out.write("            <li><a class=\"mynav-a\" href=\"index/shopspecial?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">购物商城<span></span></a>\r\n");
      out.write("                <ul style=\"display: none;\" class=\"mynav_son\">\r\n");
      out.write("                    <li><a href=\"index/actbuy?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">团代金券</a></li>\r\n");
      out.write("                    <li><a href=\"index/shopspecial?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">品牌特卖</a></li>\r\n");
      out.write("                    <li><a href=\"index/shopbulding?shoptype=building&id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">建材商城</a></li>\r\n");
      out.write("                    <li><a href=\"index/shopbulding?shoptype=electrical&id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">家具商城</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a class=\"mynav-a\" href=\"index/supervision?type=jianli&id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">我要监理</a></li>\r\n");
      out.write("            <li><a class=\"mynav-a\" href=\"index/supervision?type=jiance&id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">我要检测</a> </li>\r\n");
      out.write("            <li><a class=\"mynav-a\" href=\"http://www.wangzhong.com:8080/forum.php\" target=\"_blank\" >论坛<span></span></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"mycontainer\">\r\n");
      out.write("\t<div class=\"City_list clearfix\">\r\n");
      out.write("          <dl id=\"cityList\" class=\"City_list_modle  clearfix\">\r\n");
      out.write("              \r\n");
      out.write("          </dl>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/eshop/city.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--底部-->\r\n");
      out.write("  <div class=\"footer_top\">\r\n");
      out.write("  \t <div class=\"contentinfo\">\r\n");
      out.write("  \t \t  <div class=\"footer_top_left \">\r\n");
      out.write("  \t \t        <div class=\"footer_top_lefttitle\">“互联网+验房，上股交挂牌企业”</div>\r\n");
      out.write("  \t \t        <div class=\"row index_host_unit  clearfix\"> \r\n");
      out.write("  \t \t               <div class=\" index_circle \" align=\"center\" >\r\n");
      out.write("                             <a  title=\"享优惠\">\r\n");
      out.write("                                 <div class=\"index_host_unit_circle circle1\">\r\n");
      out.write("                                        <div class=\"index_host_unit_small_circle\"><span class=\"glyphicon glyphicon-yen\"></span></div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                             </a>\r\n");
      out.write("                             <p><span>享优惠</span><br>最全的品牌和专享折扣</p>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       <div class=\"index_circle\" align=\"center\">\r\n");
      out.write("                             <a title=\"选正品\">\r\n");
      out.write("                                 <div class=\"index_host_unit_circle circle2\">\r\n");
      out.write("                                          <div class=\"index_host_unit_small_circle\"><span class=\"glyphicon glyphicon-thumbs-up\"></span></div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                             </a>\r\n");
      out.write("                             <p><span>选正品</span><br>严管保障合格产品与服务</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"index_circle\" align=\"center\" >\r\n");
      out.write("                              <a title=\"写点评\">\r\n");
      out.write("                                     <div class=\"index_host_unit_circle circle3\">\r\n");
      out.write("                                          <div class=\"index_host_unit_small_circle \"><span class=\"glyphicon glyphicon-edit\"></span></div>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                              </a>\r\n");
      out.write("                              <p><span>写点评</span><br>向千万业主吐槽装修经验</p>\r\n");
      out.write("                         </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("  \t \t  </div>\r\n");
      out.write("  \t \t  <div class=\"footer_top_right clearfix\">\r\n");
      out.write("  \t \t  \t      <div class=\"footer_toprightbox\">\r\n");
      out.write("  \t \t  \t      \t  <div class=\"footter_toprighttitle\">网众科技官方微信</div>\r\n");
      out.write("  \t \t  \t      \t   <img src=\"images/wenxin.jpg\" alt=\"\" title=\"\" width=\"125\"/>\r\n");
      out.write("  \t \t  \t      </div>\r\n");
      out.write("  \t \t  \t       <div class=\"footer_toprightbox\">\r\n");
      out.write("  \t \t  \t      \t  <div class=\"footter_toprighttitle\">网众科技官方微博</div>\r\n");
      out.write("  \t \t  \t      \t   <img src=\"images/weibo.png\" alt=\"\" title=\"\" width=\"125\"/>\r\n");
      out.write("  \t \t  \t      </div>\r\n");
      out.write("  \t \t  </div>\r\n");
      out.write("  \t </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"footer\">\r\n");
      out.write("  \t <div class=\"footer1\">\r\n");
      out.write("        <span>友情链接：</span>\r\n");
      out.write("        <span><a href=\"\">搜房</a></span>\r\n");
      out.write("        <span class=\"index_footWrapper_vertical\">|</span>\r\n");
      out.write("        <span><a href=\"\">中国建筑新闻网-四川</a></span>\r\n");
      out.write("        <span class=\"index_footWrapper_vertical\">|</span>\r\n");
      out.write("        <span><a href=\"\">天府房产</a></span>\r\n");
      out.write("\r\n");
      out.write("        <span class=\"index_footWrapper_vertical\">|</span>\r\n");
      out.write("        <span><a href=\"\">成都楼盘网201409</a></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer2\">\r\n");
      out.write("        <!-- <span>联系方式：</span> -->\r\n");
      out.write("        <span><a href=\"index/aboutUs\">关于我们</a></span>\r\n");
      out.write("                 \r\n");
      out.write("        <span class=\"index_footWrapper_vertical\">|</span>\r\n");
      out.write("        <span><a href=\"index/callMe\">联系我们</a></span>\r\n");
      out.write("        <span class=\"index_footWrapper_vertical\">|</span>\r\n");
      out.write("        <span><a href=\"index/mzsm\">免责申明</a></span>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer2\">   \r\n");
      out.write("      <span><a href=\"\">公司总部:成都市锦江区墨香路87号9栋</a></span>&nbsp;&nbsp;\r\n");
      out.write("      <span><a > 服务热线：400-028-5998</a></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer2\" style=\"\">\r\n");
      out.write("        <span><a href=\"\">www.wangzhong.com</a></span>&nbsp;&nbsp;\r\n");
      out.write("        <span><a href=\"\">成都网众天弘科技有限公司</a></span>&nbsp;&nbsp;\r\n");
      out.write("        <span><a href=\"\">Copyrighgt©2015</a></span>&nbsp;&nbsp;\r\n");
      out.write("        <span><a href=\"\">蜀ICP备15018106号-1</a></span>\r\n");
      out.write("    </div> \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"fixright\">\r\n");
      out.write("\t\t<div class=\"fixbox\"><span class=\"glyphicon glyphicon-remove\"></span></div>\r\n");
      out.write("\t\t<a href=\"index/buyCart\"><div class=\"fixbox\"><img src=\"images/icons_16.png\" alt=\"购物车\" title=\"购物车\"></div></a>\r\n");
      out.write("\t\t<div class=\"fixbox\"><a href=\"http://v.t.sina.com.cn/share/share.php?url=http://www.shao-ming.com&title='分享web'\" target=\"_blank\"><img src=\"images/xlwb.jpg\" alt=\"分享\" title=\"分享\"></a></div>\r\n");
      out.write("\t\t<div class=\"fixbox\"><a href=\"http://v.t.qq.com/share/share.php?url=http://www.shao-ming.com&title='分享腾讯'\" target=\"_blank\"><img src=\"images/tx.jpg\" alt=\"分享\" title=\"分享\"></a></div>\r\n");
      out.write("\t\t<div class=\"fixbox\"><a href=\"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=http://www.shao-ming.com\" target=\"_blank\"><img src=\"images/qqkj.jpg\" alt=\"分享\" title=\"分享\"></a></div>\r\n");
      out.write("\t\t<div class=\"fixbox\"><a id=\"1\" href=\"javascript:scroll(0,0)\" ><img src=\"images/icons_20.png\" alt=\"回顶部\" title=\"回顶部\"></a></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/jsp/wyyf/index/top.jsp(105,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sysuser.ae_st_id }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t<dd  style=\"float:right\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<a href=\"index/intoregtie\">免费注册</a>\r\n");
        out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t<dd  style=\"float:right\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<a href=\"index/me?id=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.ae_st_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\">个人中心</a>\r\n");
        out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
        out.write("\t\t\t\t\t\t\t\t<dd   style=\"float:right\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<a href=\"system/admin/initMain\">管理中心</a>\r\n");
        out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent(null);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /WEB-INF/jsp/wyyf/index/top.jsp(121,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sysuser.ae_st_id }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<a href=\"index/loginp\" class=\"c_e60012\">请登录</a>\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t你好，【");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysuser.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("】\r\n");
        out.write("\t\t\t\t\t\t\t <a href=\"index/exit\" class=\"c_e60012\">注销</a>\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    return false;
  }
}
