/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-09-13 15:59:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wyyf.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.utils.CookieUtil;

public final class loginp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

	Cookie cookie=CookieUtil.getCookieByName(request, "userName");
	Cookie cookie2=CookieUtil.getCookieByName(request, "password");
	Cookie cookie3=CookieUtil.getCookieByName(request, "flag");
	String userName="";
	String password="";
	Boolean flag=false;
	if(cookie3!=null){
		flag=Boolean.valueOf(cookie3.getValue());
	}
	if(cookie!=null&&flag){
		userName=cookie.getValue();
	}
	if(cookie2!=null&&flag){
		password=cookie2.getValue();
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header['host']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("<title>忘记密码</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"Description\" content=\"\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/ico/ico.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/c1/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/c1/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/c1/layout.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/c1/style.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/j1/jquery/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/j1/jquery/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/j1/jquery/superSlide.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/j1/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header clearfix logintop\" style=\"\">\r\n");
      out.write("       \t<div class=\"logo logintl\"><img src=\"images/logo1.jpg\" height=\"110\"></div>\r\n");
      out.write("        <div class=\"logintc\" style=\"\">登录</div>\r\n");
      out.write("\t    <div class=\"logintr\" style=\"\">\r\n");
      out.write("\t         \t<a href=\"index.html\">回到首页</a>\r\n");
      out.write("\t    </div>\r\n");
      out.write("      </div>\r\n");
      out.write("<div class=\"bg_header\">\r\n");
      out.write("      <div class=\"logincon\">\r\n");
      out.write("      \t     <div class=\"logincon_box\">\r\n");
      out.write("      \t     \t  <div class=\"logincon_boxtop\">用户登录</div>\r\n");
      out.write("      \t          <form id=\"aaa\" class=\"loginform\" action=\"#\" method=\"post\">\r\n");
      out.write("      \t          \t<input type=\"hidden\" name=\"sfcode\" value=\"0\"/>\r\n");
      out.write("      \t          \t<div class=\"baoming_in\">\r\n");
      out.write("      \t          \t\t 账户:<input type=\"text\" name=\"username\"  autocomplete=\"on\" value=\"");
      out.print(userName);
      out.write("\">\r\n");
      out.write("      \t          \t</div>\r\n");
      out.write("      \t          \t <div class=\"baoming_in\">\r\n");
      out.write("      \t          \t\t 密码:<input type=\"password\" name=\"password\"  autocomplete=\"on\" value=\"");
      out.print(password);
      out.write("\">\r\n");
      out.write("      \t          \t</div>\r\n");
      out.write("      \t          \t<div class=\"loginform_inpu1\">\r\n");
      out.write("      \t          \t\t<input type=\"checkbox\" name=\"flag\"  value=\"1\" ");
      out.print(flag?"checked":"" );
      out.write(">\r\n");
      out.write("      \t          \t\t记住密码\r\n");
      out.write("      \t          \t\t<a href=\"index/findPwd\" style=\"\">忘记密码</a>     \t          \t  \r\n");
      out.write("      \t          \t</div>\r\n");
      out.write("      \t          \t<div class=\"baoming_bu loginform_inpu3\">\r\n");
      out.write("      \t          \t\t <input id=\"loginBtn\" value=\"登录\"  type=\"button\">\r\n");
      out.write("      \t          \t</div>\r\n");
      out.write("      \t          \t<div class=\"loginform_inpu2\">\r\n");
      out.write("      \t          \t\t<a href=\"index/intoregtie\">立即注册&gt;&gt;</a>\r\n");
      out.write("      \t          \t</div>\r\n");
      out.write("      \t          \t<input type=\"hidden\"  name=\"oldRequestUrl\"  id=\"oldRequestUrl\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${oldRequestUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("      \t          </form>\r\n");
      out.write("      \t     </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar oldRequestUrl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${oldRequestUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t//登录按钮触发事件\r\n");
      out.write("\t\t$(\"#loginBtn\").click(function() {\r\n");
      out.write("\t\t\tonLogin();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t//登录函数 \r\n");
      out.write("\tfunction onLogin(){\r\n");
      out.write("\t\tvar url = \"login\";\r\n");
      out.write("\t\tvar params=$(\"#aaa\").serialize();\r\n");
      out.write("\t\t$.post(url,params,function callback(data){  \r\n");
      out.write("\t\t\tvar resp = eval(\"(\"+data+\")\"); \r\n");
      out.write("\t\t\tif(resp.success){\r\n");
      out.write("\t\t\t\tvar oldRequestUrl=$(\"#oldRequestUrl\").val();\r\n");
      out.write("\t\t\t\tif(oldRequestUrl!=null&&oldRequestUrl!=''){\r\n");
      out.write("\t\t\t\t\tlocation.href=oldRequestUrl;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/index?r=\"+new Date().getTime();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{ \r\n");
      out.write("\t\t\t\talert(\"登录失败！\"+resp.msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
