/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-09-13 15:44:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wap;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class supervision_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/wap/jsplib.jsp", Long.valueOf(1438007830541L));
    _jspx_dependants.put("/WEB-INF/jsp/wap/header.jsp", Long.valueOf(1442159052576L));
    _jspx_dependants.put("/WEB-INF/jsp/wap/footer.jsp", Long.valueOf(1439560253065L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<base href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header['host']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('/');
      out.write('"');
      out.write('>');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html  lang=\"zh-CN\">\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\"/>\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/wap/css/bootstrap.min.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/wap/css/main.css\"/>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"indexbody\" >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<base href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header['host']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('/');
      out.write('"');
      out.write('>');
      out.write("\r\n");
      out.write("<header class=\"pindex_header clearfix\" style=\"\">\r\n");
      out.write("       <div class=\"pindex_headerleft clearfix\" style=\"\">\r\n");
      out.write("           <div style=\"\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/wap/images/plogo.png\" height=\"40\"></div>\r\n");
      out.write("           <!-- <div class=\"p_index_addr\" onclick=\"tkopeng(this,132)\"><span>成都</span><i class=\"glyphicon glyphicon-menu-down\"></i></div> -->\r\n");
      out.write("       </div>\r\n");
      out.write("      <div class=\"pindex_headerright clearfix\" style=\"\">\r\n");
      out.write("          <ul  class=\"\" style=\"\">\r\n");
      out.write("              <li><a href=\"wap/pmyzone\"><i class=\"glyphicon glyphicon-user\"></i></a></li>\r\n");
      out.write("              <li><a href=\"wap/mysession\"><i class=\"glyphicon glyphicon-shopping-cart\"></i></a></li>\r\n");
      out.write("        <!--       <li onclick=\"tkopeng(this,121)\"><i class=\"iconfont icon-fenxiang\" style=\"font-size: 1em\"></i></li> -->\r\n");
      out.write("          </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("        <div class=\"yanfang_nav\" >    \t \r\n");
      out.write("        \t <div class=\" col-xs-12 \" >\r\n");
      out.write("        \t \t <ul   class=\"nav nav-tabs design_check yf_bd\">\r\n");
      out.write("\t\t        \t \t<!-- <li class=\"nav_one nav_two3 active \"  style=\"width: 50%;margin: 0px;padding: 0px;\"><a href=\"#super_free\"data-toggle=\"tab\">免费监理</a></li> -->\r\n");
      out.write("\t\t        \t \t<li class=\"nav_one nav_two4 active\"  style=\"width: 100%;margin: 0px;padding: 0px;\"><a href=\"#super_gold\"data-toggle=\"tab\">收费监理</a></li>\r\n");
      out.write("        \t    </ul>\r\n");
      out.write("        \t </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div  class=\"myservice tab-content\" >\r\n");
      out.write("                   <!--      <div class=\"tab-pane active\" id=\"super_free\">  \r\n");
      out.write("                             <div class=\"yanfang_navcon\" style=\"min-height: 520px;\">\r\n");
      out.write("\t\t\t\t        \t \t<div class=\"yanfang_nctop design_nomol super_visoncon\"  style=\"padding: 40px 10px;\">\r\n");
      out.write("\t\t\t\t        \t \t\t  <span>XXX业主您好！\r\n");
      out.write("\t\t\t\t        \t \t\t    <p style=\"text-indent: 24px;\">系统检测到您已经在网众平台申请装修服务，我们将免费为您提供监督服务，\r\n");
      out.write("\t\t\t\t        \t \t\t    \t谢谢您对网众的认可，请预约免费监理，我们将安排专业人员全程监督您的房屋装修过程</p>\r\n");
      out.write("\t\t\t\t        \t \t\t  </span>\r\n");
      out.write("\t\t\t\t        \t \t</div>\r\n");
      out.write("\t\t\t\t        \t \t   <button class=\"btn btn-block mybuttom\" style=\"\">预约</button>\r\n");
      out.write("\t\t\t\t           </div>        \r\n");
      out.write("                        </div> -->\r\n");
      out.write("                    <!--个性设计-->    \r\n");
      out.write("                        <div class=\"tab-pane  active\" id=\"super_gold\" style=\"min-height: 520px;\">\r\n");
      out.write("       \t\t\t\t\t\t<div  class=\"yanfang_navcon\">\r\n");
      out.write("\t\t\t\t\t        \t \t<div class=\"yanfang_nctop\" >\r\n");
      out.write("\t\t\t\t                       <ul class=\"design_specile\" id=\"design_specile\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t                       </ul>\r\n");
      out.write("\t\t\t\t\t        \t \t  \r\n");
      out.write("\t\t\t\t\t        \t \t   <div class=\"loading_more\" id=\"loading_more\" ><i class=\"glyphicon glyphicon-menu-down\"></i>查看更多</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- \t<style>\r\n");
      out.write("\t.dsignmore{width: 100px;height: 50px;line-height: 50px;background-color: #F7F7F7;color: #868686;cursor: pointer;margin: 0 auto;}\r\n");
      out.write("\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\t\t\t\t<div class=\"dsignmore\" style=\"\" onclick=\"getPage(1)\" id=\"loading_more\"\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tlang=\"31\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;<i class=\"glyphicon glyphicon-arrow-down\"></i>下一页\r\n");
      out.write("\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("              \r\n");
      out.write("                       \r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<div class=\"tankuang \" ></div>\r\n");
      out.write("\t\t<div class=\"zhezhao\" ></div>\r\n");
      out.write("\t<!--底部-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer style=\"width: 100%;\">\r\n");
      out.write("    <div class=\"pindex_footer\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"wap\">首页</a></li>\r\n");
      out.write("            <li><a href=\"wap/mysession\">购物车</a></li>\r\n");
      out.write("            <li><a href=\"wap/plogin\">登录</a></li>\r\n");
      out.write("            <li><a href=\"wap/psign\">注册</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"pindex_bott\" >\r\n");
      out.write("        Copyrighgt©2015 蜀ICP备15018106号-1 成都网众天弘科技有限公司\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</body>\r\n");
      out.write("\t <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/wap/js/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("\t <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/wap/js/bootstrap.min.js\"> </script>\r\n");
      out.write("\t <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/wap/js/pmain.js\"></script>\r\n");
      out.write("\t \r\n");
      out.write("\t  <script>\r\n");
      out.write("\t \t$(document).ready(\r\n");
      out.write("\t \t\tfunction()\r\n");
      out.write("\t \t\t{\r\n");
      out.write("\t \t\t\t//取出第一页\r\n");
      out.write("\t \t\t\tgetPage(1);\r\n");
      out.write("\t \t\t\t$(\"#loading_more\").data(\"page\",1);\r\n");
      out.write("\t \t\t\t$(\"#loading_more\").click(\r\n");
      out.write("\t \t\t\t\tfunction()\r\n");
      out.write("\t \t\t\t\t{\r\n");
      out.write("\t \t\t\t\t\tvar curpage=$(\"#loading_more\").data(\"page\");\r\n");
      out.write("\t \t\t\t\t\tgetPage(++curpage);\r\n");
      out.write("\t \t\t\t\t\t$(\"#loading_more\").data(\"page\",curpage);\r\n");
      out.write("\t \t\t\t\t}\r\n");
      out.write("\t \t\t\t);\r\n");
      out.write("\t \t\t}\r\n");
      out.write("\t\t);\r\n");
      out.write("\t \t(function($){\r\n");
      out.write("\t \t\t$.getUrlParam = function(name)\r\n");
      out.write("\t \t\t{\r\n");
      out.write("\t \t\tvar reg\r\n");
      out.write("\t \t\t = new RegExp(\"(^|&)\"+\r\n");
      out.write("\t \t\t name +\"=([^&]*)(&|$)\");\r\n");
      out.write("\t \t\tvar r\r\n");
      out.write("\t \t\t = window.location.search.substr(1).match(reg);\r\n");
      out.write("\t \t\tif (r!=null) return unescape(r[2]); return null;\r\n");
      out.write("\t \t\t}\r\n");
      out.write("\t \t\t})(jQuery);\r\n");
      out.write("\t \tfunction getPage(page)\r\n");
      out.write("\t \t{\r\n");
      out.write("\t \t\t$.ajax({  \r\n");
      out.write("                type:\"POST\",  \r\n");
      out.write("                url:\"wap/supervisionpage?type=4&sqlx=\"+$.getUrlParam('sqlx')+\"&subtype=\"+$.getUrlParam('fl')+\"&page=\"+page,  \r\n");
      out.write("                dataType:\"html\",\r\n");
      out.write("                success:function(data){\r\n");
      out.write("                \t$(\"#design_specile\").append(data);\r\n");
      out.write("                },\r\n");
      out.write("                error:function(){  \r\n");
      out.write("                                  }\r\n");
      out.write("            });\r\n");
      out.write("\t \t}\r\n");
      out.write("\t </script>\r\n");
      out.write("\t \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/jsp/wap/jsplib.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/jsp/wap/jsplib.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/jsp/wap/jsplib.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("curversion");
    // /WEB-INF/jsp/wap/jsplib.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue("123457");
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /WEB-INF/jsp/wap/jsplib.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("ctx");
    // /WEB-INF/jsp/wap/jsplib.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f3.setParent(null);
    // /WEB-INF/jsp/wap/jsplib.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setVar("curversion");
    // /WEB-INF/jsp/wap/jsplib.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setValue("123457");
    int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
    if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/wap/header.jsp(17,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type != 1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\r\n");
        out.write("<nav class=\"pindex_nav\" style=\"\">\r\n");
        out.write("    <ul>\r\n");
        out.write("        <li onclick=\"pageName()\"><a  class=\"nav_back\" href=\"wap\">首页</a></li>\r\n");
        out.write("        <li onclick=\"pageName()\"><a href=\"wap/wzyf\">验房</a></li>\r\n");
        out.write("        <li onclick=\"pageName()\"><a href=\"wap/mydesign\">设计</a></li>\r\n");
        out.write("        <li onclick=\"pageName()\"><a href=\"wap/fixturejsp?sqlx=8\">装修</a></li>\r\n");
        out.write("        <li onclick=\"pageName()\"><a href=\"wap/supervision?fl=13&sqlx=10\">监理</a></li>\r\n");
        out.write("        <li onclick=\"pageName()\"><a href=\"wap/mycheck?sqlx=13\">检测</a></li>\r\n");
        out.write("        <li onclick=\"pageName()\"><a href=\"wap/myshop\">商城</a></li>\r\n");
        out.write("        <!--  <li><a  class=\"nav_back\" href=\"wap\">首页</a></li>\r\n");
        out.write("        <li><a href=\"wap/wzyf\">验房</a></li>\r\n");
        out.write("        <li ><a href=\"wap/mydesign\">设计</a></li>\r\n");
        out.write("        <li><a href=\"wap/fixturejsp\">装修</a></li>\r\n");
        out.write("        <li ><a href=\"wap/supervision?fl=13\">监理</a></li>\r\n");
        out.write("        <li ><a href=\"wap/mycheck\">检测</a></li>\r\n");
        out.write("        <li ><a href=\"wap/myshop\">商城</a></li> -->\r\n");
        out.write("    </ul>\r\n");
        out.write("</nav>\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
