/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-09-13 17:30:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wyyf.prodInfo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class intoProdInfoInto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tlds/lystags.tld", Long.valueOf(1436172035332L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--fwb-->\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\" src=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header['host']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/plugin/fwb/ueditor.config.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\" src=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header['host']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/plugin/fwb/ueditor.all.min.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\" src=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header['host']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/plugin/fwb/lang/zh-cn/zh-cn.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("/**预览功能时候的top*/\r\n");
      out.write(".edui-default .edui-dialog {\r\n");
      out.write(" top:40px !important;\r\n");
      out.write("}\r\n");
      out.write(".myfileclass{\r\n");
      out.write("\theight: auto;top: 0px;right: 0px;margin: 0px;opacity: 0;font-size: 23px; direction: ltr;cursor: pointer; width:116px;  margin-top: -34px;\r\n");
      out.write("}\r\n");
      out.write(".imgylclass{\r\n");
      out.write("\theight: 120px;width:200px;border:0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"modal-header\">\r\n");
      out.write("\t<h4  class=\"modal-title\"><span id=\"titleText\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${textTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("商品信息</span><span class=\"zhus\">注：带【<span style=\"color: red;\">*</span>】为必填项！</span></h4>\r\n");
      out.write("</div>\r\n");
      out.write("<form id=\"addForm\" class=\"form-horizontal\"  encType=\"multipart/form-data\" method=\"post\">\r\n");
      out.write("\t<!-- 商品图片管理层 -->\r\n");
      out.write("\t<div class=\"modal fade\"  id=\"img-my1-config\" tabindex=\"-1\" role=\"dialog\"  data-backdrop=\"true\"  aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-wide\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4  class=\"modal-title\"><span id=\"titleText\">商品图片管理</span></h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"preview\">\r\n");
      out.write("\t\t\t\t\t\t\t    <img id=\"imghead1\" class=\"imgylclass\" src='images/logo/default_img.jpg'><!--无预览时的默认图像，自己弄一个-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn green fileinput-button\">\r\n");
      out.write("\t\t\t\t\t\t\t    <i class=\"fa fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t    <span>选择图片</span>\r\n");
      out.write("\t\t\t\t\t\t\t    <input name=\"myfile1\" type=\"file\" onchange=\"previewImage(this,'imghead1')\" class=\"myfileclass\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-sm red\" type=\"button\" onclick=\"delimage('myfile1','imghead1','bg_st_img1')\" style=\"width:50px;\">删除</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"preview\">\r\n");
      out.write("\t\t\t\t\t\t\t    <img id=\"imghead2\" class=\"imgylclass\" src='images/logo/default_img.jpg'><!--无预览时的默认图像，自己弄一个-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn green fileinput-button\">\r\n");
      out.write("\t\t\t\t\t\t\t    <i class=\"fa fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t    <span>选择图片</span>\r\n");
      out.write("\t\t\t\t\t\t\t    <input name=\"myfile2\" type=\"file\" onchange=\"previewImage(this,'imghead2')\" class=\"myfileclass\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-sm red\" type=\"button\" onclick=\"delimage('myfile2','imghead2','bg_st_img2')\" style=\"width:50px;\">删除</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"preview\">\r\n");
      out.write("\t\t\t\t\t\t\t    <img id=\"imghead3\" class=\"imgylclass\" src='images/logo/default_img.jpg'><!--无预览时的默认图像，自己弄一个-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn green fileinput-button\">\r\n");
      out.write("\t\t\t\t\t\t\t    <i class=\"fa fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t    <span>选择图片</span>\r\n");
      out.write("\t\t\t\t\t\t\t    <input name=\"myfile3\" type=\"file\" onchange=\"previewImage(this,'imghead3')\" class=\"myfileclass\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-sm red\" type=\"button\" onclick=\"delimage('myfile3','imghead3','bg_st_img3')\" style=\"width:50px;\">删除</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"preview\">\r\n");
      out.write("\t\t\t\t\t\t\t    <img id=\"imghead4\" class=\"imgylclass\" src='images/logo/default_img.jpg'><!--无预览时的默认图像，自己弄一个-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn green fileinput-button\">\r\n");
      out.write("\t\t\t\t\t\t\t    <i class=\"fa fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t    <span>选择图片</span>\r\n");
      out.write("\t\t\t\t\t\t\t    <input name=\"myfile4\" type=\"file\" onchange=\"previewImage(this,'imghead4')\" class=\"myfileclass\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-sm red\" type=\"button\" onclick=\"delimage('myfile4','imghead4','bg_st_img4')\" style=\"width:50px;\">删除</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"preview\">\r\n");
      out.write("\t\t\t\t\t\t\t    <img id=\"imghead5\" class=\"imgylclass\" src='images/logo/default_img.jpg'><!--无预览时的默认图像，自己弄一个-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn green fileinput-button\">\r\n");
      out.write("\t\t\t\t\t\t\t    <i class=\"fa fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t    <span>选择图片</span>\r\n");
      out.write("\t\t\t\t\t\t\t    <input name=\"myfile5\" type=\"file\" onchange=\"previewImage(this,'imghead5')\" class=\"myfileclass\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-sm red\" type=\"button\" onclick=\"delimage('myfile5','imghead5','bg_st_img5')\" style=\"width:50px;\">删除</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"preview\">\r\n");
      out.write("\t\t\t\t\t\t\t    <img id=\"imghead6\" class=\"imgylclass\" src='images/logo/default_img.jpg'><!--无预览时的默认图像，自己弄一个-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn green fileinput-button\">\r\n");
      out.write("\t\t\t\t\t\t\t    <i class=\"fa fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t    <span>选择图片</span>\r\n");
      out.write("\t\t\t\t\t\t\t    <input name=\"myfile6\" type=\"file\" onchange=\"previewImage(this,'imghead6')\" class=\"myfileclass\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-sm red\" type=\"button\" onclick=\"delimage('myfile6','imghead6','bg_st_img6')\" style=\"width:50px;\">删除</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /row -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<font color=\"red\">\r\n");
      out.write("\t\t\t\t\t\t\t\t注：第一个位置的图片为商品首图（标题图），建议上传一张图片，其他位置图片随意上传。\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn default\"  id=\"coldecolde\">关闭</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 表单属性 -->\r\n");
      out.write("\t<div class=\"form-body\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">商品名称<font style=\"color: red;\">*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"bg_st_id\" type=\"text\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"bg_st_img1\" type=\"text\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"bg_st_img2\" type=\"text\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"bg_st_img3\" type=\"text\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"bg_st_img4\" type=\"text\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"bg_st_img5\" type=\"text\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"bg_st_img6\" type=\"text\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"bg_st_name\" type=\"text\" class=\"form-control\"  placeholder=\"\" datatype=\"*2-100\"  nullmsg=\"请输入商品名称！\"  errormsg=\"商品名称至少2个字符，最大100个字符\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"bg_st_numDIV\" class=\"col-md-6\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">商品编号</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"bg_st_num\" type=\"text\" class=\"form-control\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">品牌<font style=\"color: red;\">*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"pp\" type=\"text\" class=\"form-control\"  />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">型号<font style=\"color: red;\"></font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">                                                                     \r\n");
      out.write("\t\t\t\t\t\t<input name=\"xh\" type=\"text\" class=\"form-control\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">产地<font style=\"color: red;\"></font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"cd\" type=\"text\" class=\"form-control\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">材质<font style=\"color: red;\"></font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">                                                                     \r\n");
      out.write("\t\t\t\t\t\t<input name=\"cz\" type=\"text\" class=\"form-control\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">市场价格<font style=\"color: red;\">*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"bg_st_pricezg\" type=\"text\" class=\"form-control\" placeholder=\"\" datatype=\"/^(([1-9]\\d*)|0)(\\.\\d{1,2})?$/\"  errormsg=\"请输入大于0的数字，且最多2位小数！\"  nullmsg=\"请输入市场价格！\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">库存<font style=\"color: red;\">*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">                                                                     \r\n");
      out.write("\t\t\t\t\t\t<input name=\"bg_nm_storeNum\" type=\"text\" class=\"form-control\" value=\"0\" datatype=\"/^(0|([1-9]\\d*))$/\" errormsg=\"请输入10位以内的数字！\" nullmsg=\"请输入库存！\" maxlength=\"10\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">商品类型<font style=\"color: red;\">*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_my_005fselect_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">活动价格</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"bg_st_pricetj\" type=\"text\" class=\"form-control\" placeholder=\"\" value=\"0\" datatype=\"/^(([1-9]\\d*)|0)(\\.\\d{1,2})?$/\"  errormsg=\"请输入大于0的数字，且最多2位小数！\"  />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">商品二级分类<font style=\"color: red;\">*</font></label>\r\n");
      out.write("\t\t\t\t\t<div id=\"xlxDiv\" class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"threeIdData\">\r\n");
      out.write("\t\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction initData(){  \r\n");
      out.write("\t\t var  ids=\t$(\"#threeIdData\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t var bz=ids.substring(0, 1);\r\n");
      out.write("\t\t $(\"#sl option[value='\"+bz+\"']\").attr(\"selected\", \"selected\");\r\n");
      out.write("\t\t var two=\"PPLX_\"+bz;\r\n");
      out.write("\t\t $(\"#xlxDiv\").load('cat/towCat.jsp?param='+two.toString());\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction initDataTow(){  \r\n");
      out.write("\t\t\t var  ids=\t$(\"#threeIdData\").val();\r\n");
      out.write("\t\t\t var two1=ids.substring(0, 1)+\"00\"+ ids.substring(1, 2);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t $(\"#twoDivId option[value='\"+two1+\"']\").attr(\"selected\", \"selected\");\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t var two=\"PPLX_\"+ids.substring(0, 1)+\"_\"+two1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.debug(two+\"=\");\r\n");
      out.write("\t\t\t $(\"#threeDivID\").load('cat/threeCat.jsp?param='+two);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tfunction initDataThree(){  \r\n");
      out.write("\t\t\t var  ids=\t$(\"#threeIdData\").val();\r\n");
      out.write("\t\t\t console.debug(ids);\r\n");
      out.write("\t\t\t $(\"#threeId option[value='\"+ids+\"']\").attr(\"selected\", \"selected\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\tsetTimeout(\"initData()\", 50 )\r\n");
      out.write("\t\t\t\tsetTimeout(\"initDataTow()\", 900 )\r\n");
      out.write("\t\t\t\tsetTimeout(\"initDataThree()\", 1100 )\r\n");
      out.write("\t\t\t//\t$(\"#xlxDiv\").load('cat/towCat.jsp?param=PPLX_1');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t     $(\"#sl\").change(function() {\r\n");
      out.write("\t\t\t\t\tvar p1 = $(this).children('option:selected').val();//这就是selected的值 \r\n");
      out.write("\t\t\t\t\tvar two=\"PPLX_\"+p1;\r\n");
      out.write("\t\t\t\t\t$(\"#xlxDiv\").load('cat/towCat.jsp?param='+two.toString());\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//console.debug($(\"#threeId\"));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">商品三级分类<font style=\"color: red;\">*</font></label>\r\n");
      out.write("\t\t\t\t\t<div id=\"threeDivID\" class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("<!-- \t\t\t<div class=\"col-md-6\"> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"form-group\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<label class=\"control-label col-md-4\"><font style=\"color: red;\">注：</font></label> -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"col-md-8\">   -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<input  value=\"活动价格会在【发布类型】为“限时抢购”时候生效\" class=\"form-control\" style=\"color: red;\" disabled=\"disabled\" />                                                                    -->\r\n");
      out.write("<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t</div> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">是否发布<font style=\"color: red;\">*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">                                                                     \r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_my_005fselect_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">商家名称\t   </label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">  \r\n");
      out.write("\t\t\t\t                                    \r\n");
      out.write("\t\t\t\t                                                         \r\n");
      out.write("\t\t\t\t\t\t<input   readonly=\"readonly\" name=\"ae_st_nickName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ae_st_nickName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text\" class=\"form-control\"  placeholder=\"\" datatype=\"*2-100\"  nullmsg=\"请输入商品名称！\"  errormsg=\"商品名称至少2个字符，最大100个字符\"/>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">发布类型<font style=\"color: red;\">*</font></label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">                                                                     \r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_my_005fselect_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">商品图片</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"imgBtn\"  class=\"btn blue\">点击进入<i class=\"fa fa-arrow-right\"></i></button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\" id=\"isqgdiv\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">开始时间</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">                                                                     \r\n");
      out.write("\t\t\t\t\t\t<input name=\"bg_dt_startDate\" type=\"text\" class=\"form-control\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-4\">结束时间</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">                                                                     \r\n");
      out.write("\t\t\t\t\t\t<input name=\"bg_dt_endDate\" type=\"text\" class=\"form-control\"  readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-2\">商品摘要</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"bg_st_summary\" type=\"text\" class=\"form-control\" placeholder=\"\" maxlength=\"150\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /row -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label col-md-2\">商品介绍</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-10\" style=\"z-index:49;\">\r\n");
      out.write("\t\t\t\t\t\t<textarea  name=\"bg_st_prodIntro\" id=\"bg_st_prodIntro\" style=\"width:100%;height:360px;top:40px;\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t<button type=\"button\" id=\"saveBtn\"  class=\"btn blue\">保存</button>\r\n");
      out.write("\t\t<button type=\"button\"  id=\"colceupdcBtn\" class=\"btn default\" data-dismiss=\"modal\" style=\"display: none;\">关闭</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("<!-- 富文本编辑器 -->\r\n");
      out.write("<script>\r\n");
      out.write("\t//实例化编辑器\r\n");
      out.write("\tvar bg_st_prodIntro_ue = UE.getEditor('bg_st_prodIntro', {\r\n");
      out.write("\t\tautoHeightEnabled: false\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 图片预览 -->\r\n");
      out.write("<script>\r\n");
      out.write("//图片本地预览\r\n");
      out.write("function previewImage(file,targetid){\r\n");
      out.write("    if(checkPic(file)){\r\n");
      out.write("    \tvar MAXWIDTH  = 200;\r\n");
      out.write("        var MAXHEIGHT = 120;\r\n");
      out.write("        var img =$(file).parents(\"form\").first().find(\"#\"+targetid)[0];\r\n");
      out.write("        if (file.files && file.files[0]){\r\n");
      out.write("          img.onload = function(){\r\n");
      out.write("            img.width =MAXWIDTH;\r\n");
      out.write("            img.height = MAXHEIGHT;\r\n");
      out.write("          }\r\n");
      out.write("          var reader = new FileReader();\r\n");
      out.write("          reader.onload = function(evt){img.src = evt.target.result;}\r\n");
      out.write("          reader.readAsDataURL(file.files[0]);\r\n");
      out.write("        }else{\r\n");
      out.write("          var sFilter='filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src=\"';\r\n");
      out.write("          file.select();\r\n");
      out.write("          var src = document.selection.createRange().text;\r\n");
      out.write("          img.filters.item('DXImageTransform.Microsoft.AlphaImageLoader').src = src;\r\n");
      out.write("          div.innerHTML = \"<div id=divhead style='width:\"+MAXWIDTH+\"px;height:\"+MAXHEIGHT+\"px;\"+sFilter+src+\"\\\"'></div>\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("//图片删除\r\n");
      out.write("function delimage(filename,targetid,delname){\r\n");
      out.write("\tvar delurl=$(\"input[name='\"+delname+\"']\").val();\r\n");
      out.write("\tif(delurl!=null&&delurl!=\"\"){\r\n");
      out.write("\t\tbootbox.confirm('确认是否删除图片？',function(rs){\r\n");
      out.write(" \t\t\tif(rs){\r\n");
      out.write(" \t\t\t\tresetimage(filename,targetid,delname);\r\n");
      out.write(" \t\t\t\tvar url = \"files/delfiles\";\r\n");
      out.write(" \t\t\t\t$.post(url,\"delurl=\"+delurl,function callback(data){  \r\n");
      out.write(" \t\t\t\t\tvar resp = eval(\"(\"+data+\")\"); \r\n");
      out.write(" \t\t\t\t\t$(\"input[name='\"+delname+\"']\").val(\"\");\r\n");
      out.write(" \t\t\t\t\t//$(\"#saveBtn\").click();//保存一次数据\r\n");
      out.write(" \t\t\t\t});\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tresetimage(filename,targetid,delname);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("//图片重置\r\n");
      out.write("function resetimage(filename,targetid,delname){\r\n");
      out.write("\tvar obj=$(\"input[name='\"+filename+\"']\");\r\n");
      out.write("\tvar img =obj.parents(\"form\").first().find(\"#\"+targetid)[0];\r\n");
      out.write("\timg.src=\"images/logo/default_img.jpg\";\r\n");
      out.write("\tobj.after(obj.clone().val(\"\")); \r\n");
      out.write("\tobj.remove();\r\n");
      out.write("}\r\n");
      out.write("//图片选择格式限制\r\n");
      out.write("function checkPic(obj) {\r\n");
      out.write("\tvar pass =$(obj)[0]; \r\n");
      out.write("    var picPath = pass.value;\r\n");
      out.write("    var type = picPath.substring(picPath.lastIndexOf(\".\") + 1, picPath.length).toLowerCase();\r\n");
      out.write("    if (type != \"jpg\" && type != \"bmp\" && type != \"gif\" && type != \"png\") {\r\n");
      out.write("        pass.setCustomValidity(\"请上传正确的图片格式\");\r\n");
      out.write("        bootbox.alert(\"请上传正确的图片格式\");\r\n");
      out.write("        var file =$(obj) ;\r\n");
      out.write("\t\tfile.after(file.clone().val(\"\")); \r\n");
      out.write("\t\tfile.remove();\r\n");
      out.write("        return false;\r\n");
      out.write("    }else{\r\n");
      out.write("    \tpass.setCustomValidity('');\r\n");
      out.write("    \treturn true;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 初始化 -->\r\n");
      out.write("<script>\r\n");
      out.write("\t//初始化打开页面 \r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tDateInit.init();//时间控件初始化\r\n");
      out.write("\t\t//发布类型选择事件\r\n");
      out.write("\t\t$(\"#addForm select[name='bg_st_fbtpe']\").change(function(){\r\n");
      out.write("\t\t\t//如果限时抢购 \r\n");
      out.write("\t\t\tif($(this).val()=='2'){\r\n");
      out.write("\t\t\t\t$(\"#isqgdiv\").show();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#isqgdiv\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//进入新增商品信息层\r\n");
      out.write("\t\t$(\"#imgBtn\").click(function(){\r\n");
      out.write("\t\t\t$('#img-my1-config').modal('show');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//图片管理层关闭\r\n");
      out.write("\t\t$(\"#coldecolde\").click(function(){\r\n");
      out.write("\t\t\t$('#img-my1-config').modal('hide');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//点击保存事件\r\n");
      out.write("\t\t$(\"#saveBtn\").click(function(){\r\n");
      out.write("\t\t\tcheckFormValid($(\"#addForm\"),function(){\r\n");
      out.write("\t\t\t\tnewMask();\r\n");
      out.write("\t\t\t\t$(\"#addForm\").form('submit',{  \r\n");
      out.write("\t\t\t\t    url:\"wyyf/prodInfo/prodInfoSave\",  \r\n");
      out.write("\t\t\t\t    onSubmit: function(param){ \r\n");
      out.write("\t\t\t\t      // param.id=\"123\"; \r\n");
      out.write("\t\t\t\t    }, \r\n");
      out.write("\t\t\t\t    success:function(data){\r\n");
      out.write("\t\t\t\t    \tdelMask();\r\n");
      out.write("\t\t\t\t    \tvar id=$(\"#addForm input[name='bg_st_id']\").val();\r\n");
      out.write("\t\t\t\t    \tvar resp = eval(\"(\"+data+\")\"); \r\n");
      out.write("\t\t\t\t\t\tif(resp.success){\r\n");
      out.write("\t\t\t\t\t\t\t//修改\r\n");
      out.write("\t\t\t\t\t\t\tif(id!=null&&id!=\"\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tRefreshCurPage();//刷新当前页\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#colceupdcBtn\").click();\r\n");
      out.write("\t\t\t\t\t\t\t\tbootbox.alert(\"保存成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t//新增\r\n");
      out.write("\t\t\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t            bootbox.confirm('新增成功，是否重置？',function(rs){\r\n");
      out.write("\t\t\t\t\t    \t\t\tif(rs){\r\n");
      out.write("\t\t\t\t\t    \t\t\t\tloadMainPage('wyyf/prodInfo/intoProdInfoInto');//刷新本界面\r\n");
      out.write("\t\t\t\t\t    \t\t\t}\r\n");
      out.write("\t\t\t\t\t    \t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}else{ \r\n");
      out.write("\t\t\t\t\t\t\tbootbox.alert(resp.msg);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t//进入修改状态时候， 初始化数据\r\n");
      out.write("\tvar updatejsonData=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${updatejsonData }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\tif(updatejsonData!=null&&updatejsonData!=\"\"){\r\n");
      out.write("\t\tvar resp = updatejsonData;//eval(\"(\"+updatejsonData+\")\"); \r\n");
      out.write("\t\tif(resp.success){\r\n");
      out.write("\t\t\tvar obj=resp.result[0];\r\n");
      out.write("\t\t\tformload($(\"#addForm\"),obj);\r\n");
      out.write("\t\t\tsetpicfun(obj,1);\r\n");
      out.write("\t\t\tsetpicfun(obj,2);\r\n");
      out.write("\t\t\tsetpicfun(obj,3);\r\n");
      out.write("\t\t\tsetpicfun(obj,4);\r\n");
      out.write("\t\t\tsetpicfun(obj,5);\r\n");
      out.write("\t\t\tsetpicfun(obj,6);\r\n");
      out.write("\t\t\t//富文本编辑器值初始化\r\n");
      out.write("\t\t\tbg_st_prodIntro_ue.addListener(\"ready\", function () {\r\n");
      out.write("\t\t\t\tbg_st_prodIntro_ue.reset();\r\n");
      out.write("\t\t\t\tbg_st_prodIntro_ue.setContent(obj.bg_st_prodIntro);//在富文本编辑器中设置值。\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#bg_st_numDIV\").show();\r\n");
      out.write("\t\t\t$(\"#colceupdcBtn\").show();\r\n");
      out.write("\t\t\t$(\"#img-my1-config .modal-wide\").attr(\"style\",\"width: 100% !important;\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//设置初始化图片函数\r\n");
      out.write("\tfunction setpicfun(obj,i){\r\n");
      out.write("\t\tvar url=obj[\"bg_st_img\"+i];\r\n");
      out.write("\t\tif(url==null||url==\"\"){\r\n");
      out.write("\t\t\turl='images/logo/default_img.jpg'; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#imghead\"+i)[0].src=url; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_my_005fselect_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:select
    com.power.utils.tags.form.select.SelectTag _jspx_th_my_005fselect_005f0 = (new com.power.utils.tags.form.select.SelectTag());
    _jsp_instancemanager.newInstance(_jspx_th_my_005fselect_005f0);
    _jspx_th_my_005fselect_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/jsp/wyyf/prodInfo/intoProdInfoInto.jsp(210,6) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setId("sl");
    // /WEB-INF/jsp/wyyf/prodInfo/intoProdInfoInto.jsp(210,6) name = clazz type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setClazz("form-control");
    // /WEB-INF/jsp/wyyf/prodInfo/intoProdInfoInto.jsp(210,6) name = nameKey type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setNameKey("PPLX");
    _jspx_th_my_005fselect_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_my_005fselect_005f0);
    return false;
  }

  private boolean _jspx_meth_my_005fselect_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:select
    com.power.utils.tags.form.select.SelectTag _jspx_th_my_005fselect_005f1 = (new com.power.utils.tags.form.select.SelectTag());
    _jsp_instancemanager.newInstance(_jspx_th_my_005fselect_005f1);
    _jspx_th_my_005fselect_005f1.setJspContext(_jspx_page_context);
    // /WEB-INF/jsp/wyyf/prodInfo/intoProdInfoInto.jsp(310,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f1.setName("bg_st_enable");
    // /WEB-INF/jsp/wyyf/prodInfo/intoProdInfoInto.jsp(310,6) name = clazz type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f1.setClazz("form-control");
    // /WEB-INF/jsp/wyyf/prodInfo/intoProdInfoInto.jsp(310,6) name = nameKey type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f1.setNameKey("YESNO");
    _jspx_th_my_005fselect_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_my_005fselect_005f1);
    return false;
  }

  private boolean _jspx_meth_my_005fselect_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:select
    com.power.utils.tags.form.select.SelectTag _jspx_th_my_005fselect_005f2 = (new com.power.utils.tags.form.select.SelectTag());
    _jsp_instancemanager.newInstance(_jspx_th_my_005fselect_005f2);
    _jspx_th_my_005fselect_005f2.setJspContext(_jspx_page_context);
    // /WEB-INF/jsp/wyyf/prodInfo/intoProdInfoInto.jsp(333,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f2.setName("bg_st_fbtpe");
    // /WEB-INF/jsp/wyyf/prodInfo/intoProdInfoInto.jsp(333,6) name = clazz type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f2.setClazz("form-control");
    // /WEB-INF/jsp/wyyf/prodInfo/intoProdInfoInto.jsp(333,6) name = nameKey type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f2.setNameKey("SPFBLX");
    _jspx_th_my_005fselect_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_my_005fselect_005f2);
    return false;
  }
}
