/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-09-14 02:44:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8]> <html lang=\"en\" class=\"ie8 no-js\"> <![endif]-->\r\n");
      out.write("<!--[if IE 9]> <html lang=\"en\" class=\"ie9 no-js\"> <![endif]-->\r\n");
      out.write("<!--[if !IE]><!--> <html lang=\"en\" class=\"no-js\"> <!--<![endif]-->\r\n");
      out.write("<!-- BEGIN HEAD -->\r\n");
      out.write("<head>\r\n");
      out.write("\t<base href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header['host']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\">\r\n");
      out.write("\t<meta charset=\"utf-8\" /> \r\n");
      out.write("\t<title>后台管理系统</title>\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\" />\r\n");
      out.write("\t<meta content=\"\" name=\"description\" />\r\n");
      out.write("\t<meta content=\"\" name=\"author\" />\r\n");
      out.write("\t<meta name=\"MobileOptimized\" content=\"320\">\r\n");
      out.write("\t<!-- BEGIN GLOBAL MANDATORY STYLES -->          \r\n");
      out.write("\t<link href=\"assets/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/plugins/uniform/css/uniform.default.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<!-- END GLOBAL MANDATORY STYLES -->\r\n");
      out.write("\t<!-- BEGIN PAGE LEVEL STYLES --> \r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/plugins/select2/select2_metro.css\" />\r\n");
      out.write("\t<!-- END PAGE LEVEL SCRIPTS -->\r\n");
      out.write("\t<!-- BEGIN THEME STYLES --> \r\n");
      out.write("\t<link href=\"assets/css/style-metronic.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/css/style-responsive.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/css/plugins.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/css/themes/default.css\" rel=\"stylesheet\" type=\"text/css\" id=\"style_color\"/>\r\n");
      out.write("\t<link href=\"assets/css/pages/login.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"assets/css/custom.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<!-- END THEME STYLES -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header['host']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/ico/favicon.ico\" />\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t.login {\r\n");
      out.write("\t\t\t\tbackground: #777 url('assets/img/bg_login1.png') no-repeat fixed top;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t<![endif]--> \r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#javaScr_ys{\r\n");
      out.write("\t\t\tbackground: #fff;\r\n");
      out.write("\t\t\tline-height: 100px;\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t\tfont-size: 40px;\r\n");
      out.write("\t\t\tcolor: #F00;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.overlay {\r\n");
      out.write("\t\t\tbackground: #fff;\r\n");
      out.write("\t\t\tfilter: alpha(opacity=80);\r\n");
      out.write("\t\t\topacity: 0.8; \r\n");
      out.write("\t\t\ttop: 0px;\r\n");
      out.write("\t\t\tleft: 0px;\r\n");
      out.write("\t\t\twidth: 100%;\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\tz-index: 100; \r\n");
      out.write("\t\t\tposition:absolute;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style> \r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<!-- BEGIN BODY -->\r\n");
      out.write("<body class=\"login\">\r\n");
      out.write("<noscript>\r\n");
      out.write("\t\t<div id=\"javaScr_ys\" class=\"overlay\">对不起，您的浏览器禁止JavaScript脚本！</div>\r\n");
      out.write("\t</noscript>\r\n");
      out.write("\t<!-- BEGIN LOGO -->\r\n");
      out.write("\t<div class=\"logo\">\r\n");
      out.write("\r\n");
      out.write("\t\t<p>后台管理系统</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END LOGO -->\r\n");
      out.write("\t<!-- BEGIN LOGIN -->\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\t<!-- BEGIN LOGIN FORM -->\r\n");
      out.write("\t\t<form class=\"login-form\" action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"sfcode\" value=\"0\"/>\r\n");
      out.write("\t\t\t<h3 class=\"form-title\"><i class=\"fa fa-user\"></i>用户登录</h3>\r\n");
      out.write("\t\t\t");
      out.write("<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->\r\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">帐号</label>\r\n");
      out.write("\t\t\t\t<div class=\"input-icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control placeholder-no-fix\" type=\"text\" autocomplete=\"off\" placeholder=\"帐号\" name=\"username\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">密码</label>\r\n");
      out.write("\t\t\t\t<div class=\"input-icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-lock\"></i>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control placeholder-no-fix\" type=\"password\" autocomplete=\"off\" placeholder=\"密码\" name=\"password\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">验证码</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-icon input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-lock\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control placeholder-no-fix\" type=\"text\" autocomplete=\"off\" placeholder=\"验证码\" name=\"validateCode\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label visible-ie8 visible-ie9\">&emsp;</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-icon input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<img  id=\"img_c\" onclick=\"changecode();\" src=\"\" align=\"absmiddle\"  style=\"border:0px;display:inline;\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
      out.write("<div class=\"forget-password\">\r\n");
      out.write("\t\t\t\t<button id=\"loginBtn\" type=\"button\" class=\"btn blue\">\r\n");
      out.write("\t\t\t\t登录 <i class=\"m-icon-swapright m-icon-white\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<!-- <h4>忘记密码 ?</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t不用担心，请点击 <a href=\"javascript:;\"  id=\"forget-password\">这里</a>\r\n");
      out.write("\t\t\t\t\t重置你的密码.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!-- END LOGIN FORM -->        \r\n");
      out.write("\t\t<!-- BEGIN FORGOT PASSWORD FORM -->\r\n");
      out.write("\t\t<form class=\"forget-form\" action=\"index.html\" method=\"post\">\r\n");
      out.write("\t\t\t<h3 >忘记密码 ?</h3>\r\n");
      out.write("\t\t\t<p>在下面输入您的电子邮件地址来重设密码.</p>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<div class=\"input-icon\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control placeholder-no-fix\" type=\"text\" autocomplete=\"off\" placeholder=\"邮箱\" name=\"email\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-actions\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"back-btn\" class=\"btn\">\r\n");
      out.write("\t\t\t\t<i class=\"m-icon-swapleft\"></i> 返回\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn green pull-right\">\r\n");
      out.write("\t\t\t\t提交 <i class=\"m-icon-swapright m-icon-white\"></i>\r\n");
      out.write("\t\t\t\t</button>            \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!-- END FORGOT PASSWORD FORM -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END LOGIN -->\r\n");
      out.write("\t<!-- BEGIN COPYRIGHT -->\r\n");
      out.write("\t<div class=\"copyright\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END COPYRIGHT -->\r\n");
      out.write("\t<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->\r\n");
      out.write("\t<!-- BEGIN CORE PLUGINS -->   \r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"assets/plugins/respond.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/excanvas.min.js\"></script> \r\n");
      out.write("\t<![endif]-->   \r\n");
      out.write("\t<script src=\"assets/plugins/jquery-1.10.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/jquery-migrate-1.2.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("\t<script src=\"assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/jquery.blockui.min.js\" type=\"text/javascript\"></script>  \r\n");
      out.write("\t<script src=\"assets/plugins/jquery.cookie.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/uniform/jquery.uniform.min.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("\t<!-- END CORE PLUGINS -->\r\n");
      out.write("\t<!-- BEGIN PAGE LEVEL PLUGINS -->\r\n");
      out.write("\t<script src=\"assets/plugins/jquery-validation/dist/jquery.validate.min.js\" type=\"text/javascript\"></script>\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"assets/plugins/select2/select2.min.js\"></script>     \r\n");
      out.write("\t<!-- END PAGE LEVEL PLUGINS -->\r\n");
      out.write("\t<!-- Alert -->\r\n");
      out.write("\t<script src=\"assets/plugins/bootbox/bootbox.js\"></script>\r\n");
      out.write("\t<!-- BEGIN PAGE LEVEL SCRIPTS -->\r\n");
      out.write("\t<script src=\"assets/scripts/app.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/scripts/login.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<!-- END BODY -->\r\n");
      out.write("</html>\r\n");
      out.write("<!-- END PAGE LEVEL SCRIPTS --> \r\n");
      out.write("<script>\r\n");
      out.write("\t//初始化页面\r\n");
      out.write("\tjQuery(document).ready(function() {     \r\n");
      out.write("\t\tApp.init();\r\n");
      out.write("\t\tLogin.init();\r\n");
      out.write("\t\tjudge();//判断浏览器版本 \r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- END JAVASCRIPTS -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//登录按钮触发事件\r\n");
      out.write("\t\t$(\"#loginBtn\").click(function() {\r\n");
      out.write("\t\t\tonLogin();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tchangecode();//初始化验证码\r\n");
      out.write("\t});\r\n");
      out.write("\t//键盘键入函数\r\n");
      out.write("\tfunction checkKey(e) {\r\n");
      out.write("\t\tvar e=e||event;\r\n");
      out.write("\t\tvar currKey=e.keyCode||e.which||e.charCode;\r\n");
      out.write("\t\tif(13 == currKey){\r\n");
      out.write("\t\t\tif($(\"button[data-bb-handler='ok']\").length>0){\r\n");
      out.write("\t\t\t\t$(\"button[data-bb-handler='ok']\").click();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tonLogin();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//登录函数\r\n");
      out.write("\tfunction onLogin(){\r\n");
      out.write("\t\tif(judge()){\r\n");
      out.write("\t\tif ($('.login-form').validate().form()) {\r\n");
      out.write("\t\t\tvar url = \"login\";\r\n");
      out.write("\t\t\tvar params=$(\".login-form\").serialize();\r\n");
      out.write("\t\t\t$.post(url,params,function callback(data){  \r\n");
      out.write("\t\t\t\tvar resp = eval(\"(\"+data+\")\"); \r\n");
      out.write("\t\t\t\tif(resp.success){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/system/admin/initMain?r=\"+new Date().getTime();\r\n");
      out.write("\t\t\t\t}else{ \r\n");
      out.write("\t\t\t\t\tbootbox.alert(resp.msg);\r\n");
      out.write("\t\t\t\t\tif(resp.errorType==\"codeError\"){\r\n");
      out.write("\t\t\t\t\t\tchangecode();//重新获取验证码\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//键盘键入事件\r\n");
      out.write("\tdocument.onkeydown=checkKey;\r\n");
      out.write("\t//获取验证码函数\r\n");
      out.write("\tfunction changecode(){\r\n");
      out.write("\t\t$(\"#img_c\")[0].src='imageCode?r='+new Date().getTime();//加个这个目的是让IE 能识别及时的相同url访问 \r\n");
      out.write("\t\t$(\"input[name='validateCode']\").val(\"\");//清空验证码值\r\n");
      out.write("\t}\r\n");
      out.write("\t//判断IE浏览器版本\r\n");
      out.write("\tfunction judge(){\r\n");
      out.write("\t\tif(navigator.appName == \"Microsoft Internet Explorer\" && navigator.appVersion .split(\";\")[1].replace(/[ ]/g,\"\")< \"MSIE8.0\"){\r\n");
      out.write("\t\t\tbootbox.confirm('对不起！您当前浏览器版本过低，故请升级该浏览器！',function(rs){\r\n");
      out.write("\t\t\t\tif(rs){\r\n");
      out.write("\t\t\t\t\twindow.location=\"http://ie.microsoft.com/\";\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tbootbox.alert('对不起！如因网络原因不能升级，请选择非IE浏览器！');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
