/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-09-14 01:47:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wyyf.video;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class initVideoList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/wyyf/video/../../system/common/crumbsCom.jsp", Long.valueOf(1436172035598L));
    _jspx_dependants.put("/WEB-INF/tlds/lystags.tld", Long.valueOf(1436172035332L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t<!-- BEGIN PAGE TITLE & BREADCRUMB-->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"page-breadcrumb breadcrumb\">\r\n");
      out.write("\t<li>\r\n");
      out.write("\t\t<i class=\"fa fa-home\"></i>\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" id=\"cai_one\"></a> \r\n");
      out.write("\t\t<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li>\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" id=\"cai_two\"></a> \r\n");
      out.write("\t\t<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li>\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" id=\"cai_three\"></a>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"#cai_one\").text($(\"#topUlOne>li.active>a\").text());\r\n");
      out.write("\t$(\"#cai_two\").text($(\"#leftUl>li.active>a\").text());\r\n");
      out.write("\t$(\"#cai_three\").text($(\"#leftUl>li.active ul>li.active>a\").text());\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\t\t<!-- END PAGE TITLE & BREADCRUMB-->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"portlet box blue\">\r\n");
      out.write("\t<!-- BEGIN EXAMPLE TABLE PORTLET-->\r\n");
      out.write("\t<div class=\"portlet-title\">\r\n");
      out.write("\t\t<div class=\"caption\"><i class=\"fa fa-globe\"></i>视频列表</div>\r\n");
      out.write("\t\t<div class=\"actions\">\r\n");
      out.write("\t\t\t<a id=\"addAdBtn\" href=\"javascript:void(0);\" class=\"btn blue\"><i class=\"fa fa-plus\"></i> 添加</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"portlet-body\">\r\n");
      out.write("\t\t<div title=\"查询条件\">\r\n");
      out.write("\t\t\t<form id=\"queryForm\">\r\n");
      out.write("\t\t\t\t内容：<input type=\"text\" name=\"bj_st_title\" class=\"form-control\" style=\"width: 200px;display: inline;\">\r\n");
      out.write("\t\t\t\t类型：");
      if (_jspx_meth_my_005fselect_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"text\"   class=\"form-control\" style=\"width: 200px;display: none;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"querySolution\"  class=\"btn blue\"><i class=\"fa fa-search\"></i>查询</button>\r\n");
      out.write("\t\t\t\t<button type=\"reset\"  class=\"btn default\">重置</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div  id=\"tableList\" >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END EXAMPLE TABLE PORTLET-->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 添加门户设置层 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"add-config\" tabindex=\"-1\" role=\"basic\"  data-backdrop=\"static\"  aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog modal-wide\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"></button>\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\"><span id=\"addOrEditor\">新增门户设置</span><span class=\"zhus\">注：带【<span style=\"color: red;\">*</span>】为必填项！</span></h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form id=\"addForm\" action=\"#\" class=\"form-horizontal\" encType=\"multipart/form-data\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"form-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label col-md-4\">视频名称</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"br_st_id\" type=\"text\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <input name=\"br_st_userid\" type=\"text\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"br_st_addDate\" type=\"text\" value=\"\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"br_st_name\" type=\"text\" class=\"form-control\" placeholder=\"\" maxlength=\"100\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- \t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label col-md-4\">相关商品号</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"bj_st_clickurl\" type=\"text\" class=\"form-control\" placeholder=\"\"  maxlength=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t<!-- \t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label col-md-4\">序号</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"bj_nm_orderno\" type=\"text\" class=\"form-control\" value=\"0\" placeholder=\"\" datatype=\"/^\\d{1,4}$/\"  nullmsg=\"请输入门户设置序号！\" errormsg=\"门户设置序号只能为1-4位非负整数！\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- <div class=\"col-md-6\"> \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\">效果图预览</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"preview\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <img id=\"imghead\" width=\"277\" height=\"150\" border=\"0\" src='images/logo/default_img.jpg'>无预览时的默认图像，自己弄一个\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn blue fileinput-button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <i class=\"fa fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <span>选择图片</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <input id=\"myfile\" name=\"myfile\"  type=\"file\"  style=\"height: auto;top: 0px;right: 0px;margin: 0px;opacity: 0;font-size: 23px; direction: ltr;cursor: pointer; width: 253px;  margin-top: -34px;\" onchange=\"previewImage(this)\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t<!--/row-->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label col-md-2\">视频地址</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea name=\"br_st_url\" class=\"form-control\" rows=\"3\" maxlength=\"5000\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- <div class=\"row\" style=\"margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<font color=\"red\">\r\n");
      out.write("\t\t\t\t\t\t\t\t注：\r\n");
      out.write("\t\t\t\t\t\t\t\t<br/>&emsp;一、设置网站LOGO，操作：【类型】设为“网站LOGO”，然后【选择图片】，然后选择【是否启用】为“是”最后保存。\r\n");
      out.write("\t\t\t\t\t\t\t\t<br/>&emsp;&emsp;&emsp;特别注意：可以设置多个网站LOGO，但是只会随机选择一个启用的LOGO设置。\r\n");
      out.write("\t\t\t\t\t\t\t\t<br/>&emsp;二、设置网站名，操作：【类型】设为“网站名”，然后设置【内容】为'XX商城'，然后选择【是否启用】为“是”最后保存。\r\n");
      out.write("\t\t\t\t\t\t\t\t<br/>&emsp;&emsp;&emsp;特别注意：可以设置多个网站名，但是只会随机选择一个启用的网站名设置。\r\n");
      out.write("\t\t\t\t\t\t\t\t<br/>&emsp;三、设置首页大广告，操作：【类型】设为“首页大广告”，然后设置【选择图片】，然后可设置【内容】为一个URL地址,然后选择【是否启用】为“是”最后保存。\r\n");
      out.write("\t\t\t\t\t\t\t\t<br/>&emsp;&emsp;&emsp;特别注意：可以设置多个首页大广告，最多不能超过5张。每个广告的点击都会跳转到设置好的URL地址。【序号】为显示的顺序。\r\n");
      out.write("\t\t\t\t\t\t\t\t<br/>&emsp;四、设置首页精品推荐，操作：【类型】设为“首页精品推荐”，然后【选择图片】，然后可设置【内容】为一个商品编号,然后选择【是否启用】为“是”最后保存。\r\n");
      out.write("\t\t\t\t\t\t\t\t<br/>&emsp;&emsp;&emsp;特别注意：可以设置多个首页精品推荐，最多不能超过5个。每个精品推荐的点击都会跳转到设置商品编号详情页面。【序号】为显示的顺序。\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"saveBtn\"  class=\"btn blue\">保存</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn default\" data-dismiss=\"modal\">取消</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.modal-content -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.modal-dialog -->\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t//初始化打开页面 \r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tloadotherPage(\"&pageIndex=1&pageSize=10\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//进入新增层\r\n");
      out.write("\t\t$(\"#addAdBtn\").click(function(){\r\n");
      out.write("\t\t\t$(\"#addForm\")[0].reset();\r\n");
      out.write("\t\t\tinitValidForm($(\"#addForm\"));\r\n");
      out.write("\t\t\t//document.getElementById('imghead').src=\"images/logo/default_img.jpg\";//初始化图片选择\r\n");
      out.write("\t\t\t$(\"#addOrEditor\").html(\"新增视频设置\");\r\n");
      out.write("\t\t\t$('#add-config').modal('show');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//新增-修改层的保存功能\r\n");
      out.write("\t\t$(\"#saveBtn\").click(function(){\r\n");
      out.write("\t\t\tcheckFormValid($(\"#addForm\"),function(){\r\n");
      out.write("\t\t\t\tnewMask();\r\n");
      out.write("\t\t\t\tvar id=$(\"#addForm input[name='br_st_id']\").val();\r\n");
      out.write("\t\t\t\t$(\"#addForm\").form('submit',{\r\n");
      out.write("\t\t\t\t\turl:\"wyyf/video/sysVideoAdd\",  \r\n");
      out.write("\t\t\t\t     onSubmit: function(param){ \r\n");
      out.write("\t\t\t\t    }, \r\n");
      out.write("\t\t\t\t    success:function(data){ \r\n");
      out.write("\t\t\t\t\t\tdelMask();\r\n");
      out.write("\t\t\t\t    \tvar resp = eval(\"(\"+data+\")\"); \r\n");
      out.write("\t\t\t\t\t\tif(resp.success){\r\n");
      out.write("\t\t\t\t\t\t\tRefreshCurPage();//刷新当前页，--该函数在 commonList.jsp中\r\n");
      out.write("\t\t\t\t\t\t\t//修改\r\n");
      out.write("\t\t\t\t\t\t\tif(id!=null&&id!=\"\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#add-config').modal('hide');\r\n");
      out.write("\t\t\t\t\t\t\t\tbootbox.alert(\"编辑成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t//新增\r\n");
      out.write("\t\t\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#add-config').modal('hide');\r\n");
      out.write("\t\t\t\t\t\t\t\tbootbox.alert(\"新增成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}else{ \r\n");
      out.write("\t\t\t\t\t\t\tbootbox.alert(resp.msg);\r\n");
      out.write("\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//查询\r\n");
      out.write("\t\t$(\"#querySolution\").click(function(){\r\n");
      out.write("\t\t\tClickFindPage();//查询到第1页，--该函数在 commonList.jsp中\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t//替换主题内容的函数\r\n");
      out.write("\tfunction loadotherPage(params) {\r\n");
      out.write("\t\tvar param=$(\"#queryForm\").serialize();//条件参数\r\n");
      out.write("\t\tvar url=\"wyyf/video/videoList\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar xsl=$(\"#commonid_column_toggler input[name='ISSHOWCOLUMS'][type='checkbox']:checked\").serialize();//显示列的控制\r\n");
      out.write("\t\tif(xsl){\r\n");
      out.write("\t\t\tparam+=\"&\"+xsl;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tnewMask();\r\n");
      out.write("\t\tjQuery(\"#tableList\").load(url,param+params+\"&rr=\"+new Date().getTime(),function(response,status,xhr){\r\n");
      out.write("\t\t\tdelMask();\r\n");
      out.write("\t\t\tif(xhr.status==403){\r\n");
      out.write("\t\t\t\t$(this).html(xhr.responseText);\r\n");
      out.write("\t\t\t}else if(xhr.status==404){\r\n");
      out.write("\t\t\t\t$(this).html(xhr.responseText);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//修改门户设置\r\n");
      out.write("\tfunction editAdvertisement(obj){\r\n");
      out.write("\t\t$(\"#addForm\")[0].reset();\r\n");
      out.write("\t\tvar brid=$(obj).parents(\"tr\").first().find(\"input[type='checkbox'].checkboxes\").val();\r\n");
      out.write("\t\talert(brid);\r\n");
      out.write("\t\tvar url = \"wyyf/video/findVideoById\";\r\n");
      out.write("\t\tnewMask();\r\n");
      out.write("\t\t$.post(url,\"brid=\"+brid,function callback(data){   \r\n");
      out.write("\t\t\tdelMask();\r\n");
      out.write("\t\t\tvar resp = eval(\"(\"+data+\")\"); \r\n");
      out.write("\t\t\tif(resp.success){\r\n");
      out.write("\t\t\t\tvar obj=resp.result[0];\r\n");
      out.write("\t\t\t\tformload($(\"#addForm\"),obj);\r\n");
      out.write("\t\t\t\t/* if(obj.ag_st_url == null || obj.ag_st_url == \"\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('imghead').src=\"images/logo/default_img.jpg\";//初始化图片选择\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('imghead').src=obj.ag_st_url;\r\n");
      out.write("\t\t\t\t} */\r\n");
      out.write("\t\t\t\t$(\"#addOrEditor\").html(\"编辑视频设置\");\r\n");
      out.write("\t\t\t\tinitValidForm($(\"#addForm\"));//清除表单验证样式 \r\n");
      out.write("\t\t\t\t$('#add-config').modal('show');\r\n");
      out.write("\t\t\t}else{ \r\n");
      out.write("\t\t\t\tbootbox.alert(resp.msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//删除门户设置 \r\n");
      out.write("\t/* function delAdvertisement(obj){\r\n");
      out.write("\t\tbootbox.confirm('确定是否删除？',function(rs){\r\n");
      out.write("\t\t\tif(rs){\r\n");
      out.write("\t\t\t\tnewMask();\r\n");
      out.write("\t\t\t\tvar advertisementId=$(obj).parents(\"tr\").first().find(\"input[type='checkbox'].checkboxes\").val();\r\n");
      out.write("\t\t\t\tvar url = \"wyyf/video/advertisementDelete\";\r\n");
      out.write("\t\t\t\t$.post(url,\"advertisementId=\"+advertisementId,function callback(data){  \r\n");
      out.write("\t\t\t\t\tdelMask();\r\n");
      out.write("\t\t\t\t\tvar resp = eval(\"(\"+data+\")\"); \r\n");
      out.write("\t\t\t\t\tif(resp.success){\r\n");
      out.write("\t\t\t\t\t\tRefreshCurPage();//刷新当前页，--该函数在 commonList.jsp中\r\n");
      out.write("\t\t\t\t\t\tbootbox.alert(resp.msg);\r\n");
      out.write("\t\t\t\t\t}else{ \r\n");
      out.write("\t\t\t\t\t\tbootbox.alert(resp.msg);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t  //取消操作\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t} */\r\n");
      out.write("</script> \r\n");
      out.write("<script>\r\n");
      out.write("//图片本地预览\r\n");
      out.write("function previewImage(file){\r\n");
      out.write("    if(checkPic(file)){\r\n");
      out.write("    \tvar MAXWIDTH  = 277;\r\n");
      out.write("        var MAXHEIGHT = 150;\r\n");
      out.write("        var img =$(file).parents(\"form\").first().find(\"#imghead\")[0];\r\n");
      out.write("        if (file.files && file.files[0]){\r\n");
      out.write("          img.onload = function(){\r\n");
      out.write("            img.width =277;\r\n");
      out.write("            img.height = 150;\r\n");
      out.write("          }\r\n");
      out.write("          var reader = new FileReader();\r\n");
      out.write("          reader.onload = function(evt){img.src = evt.target.result;}\r\n");
      out.write("          reader.readAsDataURL(file.files[0]);\r\n");
      out.write("        }else{\r\n");
      out.write("          var sFilter='filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src=\"';\r\n");
      out.write("          file.select();\r\n");
      out.write("          var src = document.selection.createRange().text;\r\n");
      out.write("          img.filters.item('DXImageTransform.Microsoft.AlphaImageLoader').src = src;\r\n");
      out.write("          div.innerHTML = \"<div id=divhead style='width:277px;height:150px;\"+sFilter+src+\"\\\"'></div>\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("//图片选择格式限制\r\n");
      out.write("function checkPic(obj) {\r\n");
      out.write("\tvar pass =$(obj).parents(\"form\").first().find(\"#myfile\")[0];\r\n");
      out.write("    var picPath = pass.value;\r\n");
      out.write("    var type = picPath.substring(picPath.lastIndexOf(\".\") + 1, picPath.length).toLowerCase();\r\n");
      out.write("    if (type != \"jpg\" && type != \"bmp\" && type != \"gif\" && type != \"png\") {\r\n");
      out.write("        pass.setCustomValidity(\"请上传正确的图片格式\");\r\n");
      out.write("        bootbox.alert(\"请上传正确的图片格式\");\r\n");
      out.write("        //$(\"#myfile\").val(\"\");\r\n");
      out.write("        var file = $(\"input[name='myfile']\") \r\n");
      out.write("\t\tfile.after(file.clone().val(\"\")); \r\n");
      out.write("\t\tfile.remove();\r\n");
      out.write("        return false;\r\n");
      out.write("    }else{\r\n");
      out.write("    \tpass.setCustomValidity('');\r\n");
      out.write("    \treturn true;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_my_005fselect_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:select
    com.power.utils.tags.form.select.SelectTag _jspx_th_my_005fselect_005f0 = (new com.power.utils.tags.form.select.SelectTag());
    _jsp_instancemanager.newInstance(_jspx_th_my_005fselect_005f0);
    _jspx_th_my_005fselect_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/jsp/wyyf/video/initVideoList.jsp(23,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setName("bj_st_type");
    // /WEB-INF/jsp/wyyf/video/initVideoList.jsp(23,7) name = clazz type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setClazz("form-control");
    // /WEB-INF/jsp/wyyf/video/initVideoList.jsp(23,7) name = nameKey type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setNameKey("ADVERTADTYPE");
    // /WEB-INF/jsp/wyyf/video/initVideoList.jsp(23,7) name = isAddDefaltOption type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setIsAddDefaltOption(new java.lang.Boolean(true));
    // /WEB-INF/jsp/wyyf/video/initVideoList.jsp(23,7) name = defaltOptionKey type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setDefaltOptionKey("");
    // /WEB-INF/jsp/wyyf/video/initVideoList.jsp(23,7) name = defaltOptionValue type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setDefaltOptionValue("-请选择-");
    // /WEB-INF/jsp/wyyf/video/initVideoList.jsp(23,7) name = style type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fselect_005f0.setStyle("width: 200px;display: inline;");
    _jspx_th_my_005fselect_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_my_005fselect_005f0);
    return false;
  }
}
